# Generated by Django 5.1.1 on 2024-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='merchantId',
        ),
        migrations.AddField(
            model_name='payment',
            name='ProductName',
            field=models.CharField(default='Video Editing Bundle', max_length=250),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
